name: Build Asset Bundles

on:
  workflow_dispatch:

jobs:
  buildAssetBundles:
    name: Build Asset Bundles 📦
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-AssetBundles

      - name: Free Unity License Activation
        uses: game-ci/unity-request-activation-file@v4
        id: step1
        with:
          unityVersion: 2022.3.10f1

      - name: Run Unity Builder
        uses: game-ci/unity-builder@v4
        with:
          projectPath: .
          unityVersion: 2022.3.10f1
          targetPlatform: StandaloneWindows64
          buildMethod: CreateAssetBundles.BuildAllAssetBundles

      - name: Upload AssetBundles
        uses: actions/upload-artifact@v4
        with:
          name: My-Asset-Bundles
          path: Assets/AssetBundles/
