name: Build Asset Bundles

on:
  workflow_dispatch:

jobs:
  buildAssetBundles:
    name: Build Asset Bundles 📦
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-AssetBundles

      - name: Run Unity Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: "団" # Специальный символ-заглушка для обхода проверки персональной лицензии
        with:
          projectPath: .
          unityVersion: 2022.3.10f1
          targetPlatform: StandaloneWindows64
          buildMethod: CreateAssetBundles.BuildAllAssetBundles
          allowDirtyBuild: true
